### ISSUE TITLE
Let's release ndx-pose? 

### ISSUE THREAD

**Issue by AlexEMG** [rly/ndx-pose#2]
Compare to issue: https://github.com/DeepLabCut/DLC2NWB/issues/5

**Comment by AlexEMG** [comment]
Yes, let's release it!

**Comment by rly** [comment]
ndx-pose 0.1.1 is now on [PyPI](https://pypi.org/project/ndx-pose/). I merged a few minor changes today which should not affect DLC2NWB but please let me know if there are any issues.

**Comment by AlexEMG** [comment]
Great, we are also up and running https://pypi.org/project/dlc2nwb/
